"""empty message

Revision ID: 9f36b04b728e
Revises: None
Create Date: 2016-11-01 14:40:57.995000

"""

# revision identifiers, used by Alembic.
revision = '9f36b04b728e'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
