"""empty message

Revision ID: e8dde2e31305
Revises: 9f36b04b728e
Create Date: 2016-11-01 16:23:17.825000

"""

# revision identifiers, used by Alembic.
revision = 'e8dde2e31305'
down_revision = '9f36b04b728e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email')
    ### end Alembic commands ###
